import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Loader2 } from 'lucide-react';
import api from '../../api/api';

export default function EditProperty() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  
  const [formData, setFormData] = useState({
    type: 'APARTMENT',
    title: '',
    city: '',
    locality: '',
    address: '',
    pincode: '',
    bhk: 1,
    area: '',
    floor: '',
    totalFloors: '',
    rent: '',
    deposit: '',
    availableFrom: '',
    rentNegotiable: false,
    furnished: 'SEMI_FURNISHED',
    description: ''
  });

  useEffect(() => {
    const fetchProperty = async () => {
      try {
        const response = await api.get(`/api/properties/${id}`);
        const prop = response.data;
        setFormData({
          type: prop.type || 'APARTMENT',
          title: prop.title || '',
          city: prop.city || '',
          locality: prop.locality || '',
          address: prop.address || '',
          pincode: prop.pincode || '',
          bhk: prop.bhk || 1,
          area: prop.area || '',
          floor: prop.floor || '',
          totalFloors: prop.totalFloors || '',
          rent: prop.rent || '',
          deposit: prop.deposit || '',
          availableFrom: prop.availableFrom ? new Date(prop.availableFrom).toISOString().split('T')[0] : '',
          rentNegotiable: prop.rentNegotiable || false,
          furnished: prop.furnished || 'SEMI_FURNISHED',
          description: prop.description || ''
        });
      } catch (error) {
        console.error('Failed to fetch property details:', error);
        alert('Could not load property data.');
      } finally {
        setLoading(false);
      }
    };
    fetchProperty();
  }, [id]);

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSaving(true);
    try {
      await api.put(`/api/owner/properties/${id}`, formData);
      alert('Property updated successfully!');
      navigate('/owner/my-properties');
    } catch (error) {
      console.error('Error updating property:', error);
      alert('Failed to update property. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '60vh' }}>
        <Loader2 size={48} className="animate-spin" color="var(--color-primary)" />
      </div>
    );
  }

  const sectionStyle = {
    backgroundColor: 'var(--color-white)',
    padding: '24px',
    borderRadius: '12px',
    marginBottom: '20px',
    border: '1px solid var(--color-bebe)'
  };

  const titleStyle = {
    fontFamily: 'var(--font-headline)',
    fontSize: '18px',
    fontWeight: 'bold',
    marginBottom: '16px',
    color: 'var(--color-on-surface)'
  };

  const labelStyle = {
    display: 'block',
    fontSize: '14px',
    color: 'var(--color-foggy)',
    marginBottom: '6px'
  };

  const gridStyle = {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '16px'
  };

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '24px 16px' }}>
      <h1 style={{ fontFamily: 'var(--font-headline)', marginBottom: '24px' }}>Edit Property</h1>
      
      <form onSubmit={handleSubmit}>
        {/* Section 1 - Basic Info */}
        <div style={sectionStyle} className="card">
          <h2 style={titleStyle}>Basic Information</h2>
          <div style={gridStyle}>
            <div>
              <label style={labelStyle}>Property Type</label>
              <select name="type" className="input" value={formData.type} onChange={handleChange} required style={{ width: '100%' }}>
                <option value="APARTMENT">Apartment</option>
                <option value="INDEPENDENT_HOUSE">Independent House</option>
                <option value="VILLA">Villa</option>
              </select>
            </div>
            <div>
              <label style={labelStyle}>Title (Auto-generated by system usually)</label>
              <input type="text" name="title" className="input" value={formData.title} readOnly style={{ width: '100%', backgroundColor: '#f3f4f6', cursor: 'not-allowed' }} />
            </div>
          </div>
        </div>

        {/* Section 2 - Location */}
        <div style={sectionStyle} className="card">
          <h2 style={titleStyle}>Location</h2>
          <div style={{ ...gridStyle, marginBottom: '16px' }}>
            <div>
              <label style={labelStyle}>City</label>
              <input type="text" name="city" className="input" value={formData.city} onChange={handleChange} required style={{ width: '100%' }} />
            </div>
            <div>
              <label style={labelStyle}>Locality</label>
              <input type="text" name="locality" className="input" value={formData.locality} onChange={handleChange} required style={{ width: '100%' }} />
            </div>
          </div>
          <div style={{ marginBottom: '16px' }}>
            <label style={labelStyle}>Full Address</label>
            <input type="text" name="address" className="input" value={formData.address} onChange={handleChange} required style={{ width: '100%' }} />
          </div>
          <div>
            <label style={labelStyle}>Pincode</label>
            <input type="text" name="pincode" className="input" value={formData.pincode} onChange={handleChange} required style={{ width: '100%', maxWidth: '200px' }} />
          </div>
        </div>

        {/* Section 3 - Details */}
        <div style={sectionStyle} className="card">
          <h2 style={titleStyle}>Property Details</h2>
          <div style={gridStyle}>
            <div>
              <label style={labelStyle}>BHK</label>
              <input type="number" name="bhk" className="input" value={formData.bhk} onChange={handleChange} min="1" required style={{ width: '100%' }} />
            </div>
            <div>
              <label style={labelStyle}>Carpet Area (sq ft)</label>
              <input type="number" name="area" className="input" value={formData.area} onChange={handleChange} required style={{ width: '100%' }} />
            </div>
            <div>
              <label style={labelStyle}>Floor Number</label>
              <input type="number" name="floor" className="input" value={formData.floor} onChange={handleChange} required style={{ width: '100%' }} />
            </div>
            <div>
              <label style={labelStyle}>Total Floors</label>
              <input type="number" name="totalFloors" className="input" value={formData.totalFloors} onChange={handleChange} required style={{ width: '100%' }} />
            </div>
          </div>
        </div>

        {/* Section 4 - Rent */}
        <div style={sectionStyle} className="card">
          <h2 style={titleStyle}>Rent & Availability</h2>
          <div style={gridStyle}>
            <div>
              <label style={labelStyle}>Monthly Rent (₹)</label>
              <input type="number" name="rent" className="input" value={formData.rent} onChange={handleChange} required style={{ width: '100%' }} />
            </div>
            <div>
              <label style={labelStyle}>Security Deposit (₹)</label>
              <input type="number" name="deposit" className="input" value={formData.deposit} onChange={handleChange} required style={{ width: '100%' }} />
            </div>
            <div>
              <label style={labelStyle}>Available From</label>
              <input type="date" name="availableFrom" className="input" value={formData.availableFrom} onChange={handleChange} required style={{ width: '100%' }} />
            </div>
            <div style={{ display: 'flex', alignItems: 'center', marginTop: '24px' }}>
              <label style={{ display: 'flex', alignItems: 'center', cursor: 'pointer', fontSize: '14px', color: 'var(--color-on-surface)' }}>
                <input type="checkbox" name="rentNegotiable" checked={formData.rentNegotiable} onChange={handleChange} style={{ marginRight: '8px', width: '18px', height: '18px' }} />
                Rent is negotiable
              </label>
            </div>
          </div>
        </div>

        {/* Section 5 - Furnishing */}
        <div style={sectionStyle} className="card">
          <h2 style={titleStyle}>Furnishing & Description</h2>
          <div style={{ marginBottom: '16px' }}>
            <label style={labelStyle}>Furnishing Status</label>
            <select name="furnished" className="input" value={formData.furnished} onChange={handleChange} required style={{ width: '100%', maxWidth: '300px' }}>
              <option value="UNFURNISHED">Unfurnished</option>
              <option value="SEMI_FURNISHED">Semi-Furnished</option>
              <option value="FULLY_FURNISHED">Fully Furnished</option>
            </select>
          </div>
          <div>
            <label style={labelStyle}>Description</label>
            <textarea 
              name="description" 
              className="input" 
              value={formData.description} 
              onChange={handleChange} 
              rows="4" 
              placeholder="Tell us more about the property..."
              required 
              style={{ width: '100%', resize: 'vertical' }}
            />
          </div>
        </div>

        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '16px', marginTop: '24px' }}>
          <button 
            type="button" 
            onClick={() => navigate(-1)}
            style={{ padding: '10px 20px', borderRadius: '8px', border: '1px solid var(--color-bebe)', background: 'transparent', cursor: 'pointer', fontWeight: 'bold' }}
            disabled={saving}
          >
            Cancel
          </button>
          <button 
            type="submit" 
            className="btn-primary"
            style={{ padding: '10px 24px', display: 'flex', alignItems: 'center', gap: '8px' }}
            disabled={saving}
          >
            {saving ? <Loader2 size={18} className="animate-spin" /> : null}
            {saving ? 'Saving...' : 'Save Changes'}
          </button>
        </div>
      </form>
    </div>
  );
}
